version: "3.5"
services:
  api:
    container_name: otus-calendar-api
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - database
    volumes:
      - ..:/app
    environment:
      HOTRELOAD_APP_CMD: "api-server"
    env_file:
      - ./.env
    entrypoint: ["/usr/local/bin/air", "-c", "/etc/air/api.toml"]
    networks:
      - otus-network

  grpc:
    container_name: otus-calendar-grpc
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    ports:
      - "6565:6565"
    depends_on:
      - database
    volumes:
      - ..:/app
    environment:
      HOTRELOAD_APP_CMD: "grpc-server"
    env_file:
      - ./.env
    entrypoint: ["/usr/local/bin/air", "-c", "/etc/air/api.toml"]
    networks:
      - otus-network

  scheduler:
    container_name: otus-calendar-scheduler
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    depends_on:
      - database
      - message_bus
    volumes:
      - ..:/app
    env_file:
      - ./.env
    entrypoint: ["/usr/local/bin/air", "-c", "/etc/air/scheduler.toml"]
    networks:
      - otus-network

  notificator:
    container_name: otus-calendar-notificator
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    depends_on:
      - database
      - message_bus
    volumes:
      - ..:/app
    env_file:
      - ./.env
    entrypoint: ["/usr/local/bin/air", "-c", "/etc/air/notificator.toml"]
    networks:
      - otus-network

  database:
    container_name: otus-calendar-database
    image: postgres:12.1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ./.env
    networks:
      - otus-network

  message_bus:
    container_name: otus-calendar-messagebus
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${MESSAGE_BUS_USER}
      RABBITMQ_DEFAULT_PASS: ${MESSAGE_BUS_PASS}
    env_file:
      - ./.env
    networks:
      - otus-network

  migrations:
    container_name: otus-calendar-migrations
    build:
      context: ..
      dockerfile: deployments/images/migrator/Dockerfile
    depends_on:
      - database
    volumes:
      - ./migrations:/migrations
    env_file:
      - ./.env
    networks:
      - otus-network
    entrypoint:
      - "/usr/local/bin/goose"
      - "postgres"
      - "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"

networks:
  otus-network:
    name: otus-network
